### ISSUE TITLE
getNetworkUploadSpeed() function does not work now.

### ISSUE THREAD

**Issue by sawyerbutton** [kenigbolo/network-speed#1]
The host link for the function 'www.postcatcher.in' does not work correctly recently, is there any possible way to fix this problem?

**Comment by kenigbolo** [comment]
Hi @sawyerbutton If www.postcatcher.in doesn't work anymore then you'll have to substitute this for another similar service that has the same functionality of you create an endpoint in your app and use that endpoint (if your app is live). I'll close this issue for now 🙂
