### ISSUE TITLE
getUploadSpeed() returns Infinity

### ISSUE THREAD

**Issue by christianbalderrama** [kenigbolo/network-speed#3]
Sometimes the result is `0.15` and often it is `Infinity`.

**Comment by kenigbolo** [comment]
@christianbalderrama Thanks for this report. I'd look into this and let you know once I pinpoint the issue and fix it.

**Comment by christianbalderrama** [comment]
Thank you. Also I have an issue with the download as well, I'll create a PR would be glad to contribute with this package @kenigbolo

**Comment by kenigbolo** [comment]
@christianbalderrama contributions are absolutely welcomed. I’ll be looking forward to your PR

**Comment by christianbalderrama** [comment]
Hi @kenigbolo what is the basis of the `fileSize`? It is not documented if it is `kb` or `bytes`

Thanks!

**Comment by kenigbolo** [comment]
@christianbalderrama in bytes

**Comment by kenigbolo** [comment]
@christianbalderrama Still willing to work on this?

**Comment by whiteadi** [comment]
![screenshot 2019-03-08 13 51 32](https://user-images.githubusercontent.com/4496789/54029619-50a85b80-41a9-11e9-86b7-f91df7d86f61.png)

sometimes Infinity sometimes good values but also sometimes takes a lot, look at 33 seconds :)

**Comment by kenigbolo** [comment]
@whiteadi This definitely is a valid issue. Unfortunately I haven’t managed to make our time to work on this yet. I’d give it some time next weekend and try to fix this limitation. Thanks for letting me know anyways, appreciate the feedback
