### ISSUE TITLE
Unclear on filesize

### ISSUE THREAD

**Issue by aaronmgdr** [kenigbolo/network-speed#52]
Based on the example it looks like the baseURl is asking for 50,000,000 bytes while the given size looks like 500,000  is this right? 

```
const baseUrl = 'http://eu.httpbin.org/stream-bytes/50000000';
  const fileSize = 500000;
```

**Comment by kenigbolo** [comment]
@aaronmgdr Fixed this in the latest release. The documentation and examples now reflect the accurate number. The file size is now explicitly stated to be in `bytes` and the example code snippet now has `500000` in both the stream bytes URL and the file size as well. Thanks for raising this issue.

**Comment by aaronmgdr** [comment]
cool!
